title: Jaroslav Henner  # Add a space after the period

logo: jaro.png # Use a relative path to logo image 

description: Kouč seberozvoje a IT inženýr.

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "" # Verify ownership through Search Console  

email: jaroslav.henner@gmail.com # Allow visitors to contact you
